# This is a basic workflow to help you get started with Actions

name: deploy to vps

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sudo apt-get update
            sudo -E bash /home/${{ secrets.USERNAME }}/nodesource_setup.sh
            sudo apt-get install -y nodejs
            sudo apt-get install docker-compose-plugin
            cd /home/${{ secrets.USERNAME }}/Deploy/blog
            git switch main
            git pull origin main
            docker compose -f ./deploy-compose.yaml pull
            docker-compose up -d
